In [1]:
import pandas as pd
from langchain.llms import OpenAI
from langchain.agents.agent_types import AgentType
from langchain.chat_models import ChatOpenAI
from util import local_settings



data = pd.read_csv("Data/Metadata/movies.csv")


# so do not use the dataframes agent


#!python -m spacy download en_core_web_md


#import spacy

#nlp = spacy.load("en_core_web_md")

import numpy as np

#from sentence_transformers import SentenceTransformer
#model = SentenceTransformer("all-MiniLM-L6-v2")
#text_embeddings = model.encode(texts)

#from sklearn.metrics.pairwise import cosine_similarity
#text_embeddings_dict = dict(zip(texts, list(text_embeddings)))

######################
#embeddings = OpenAIEmbeddings()

'''texts =  [
    "Harrison worked at kensho",
    "bears like to eat honey",
    "Each day is a new opportunity for growth and success.",
    "I believe in my abilities and trust the journey I am on.",
    "I radiate positivity and attract abundance into my life.",
    "I am deserving of love, happiness, and all the good things life has to offer.",
]
'''
#retriever = FAISS.from_texts(texts, embeddings)


#################


from fuzzywuzzy import fuzz
from fuzzywuzzy import process
import pandas as pd

# Assuming your dataset is in a CSV file named 'movies.csv', adjust the filename and path accordingly

sk-jkvbmGoy450Esp9B8Zo9T3BlbkFJH6tJ4

c:\Users\Ilona\Documents\GitHub\Capstone-Project\env\Lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [1]:
###############################################################################################
""" Creating User Database"""
import sqlite3

# Connect to SQLite database (creates one if doesn't exist)
conn = sqlite3.connect('Data/users_data.db')
cursor = conn.cursor()

# Create a table for user profiles if not exists
cursor.execute('''
    CREATE TABLE IF NOT EXISTS Users(
        id INTEGER PRIMARY KEY,
        username TEXT,
        age INTEGER,
        gender TEXT,
        fav_entertainment TEXT,
        least_fav_entertainment TEXT,
        likes TEXT,
        dislikes TEXT,
        movie_watching_freq TEXT,
        show_watching_freq TEXT,
        reading_freq TEXT
    )
''')

# Function to insert user profile into the database
def insert_user_profile(username, age, gender, fav_entertainment, least_fav_entertainment, likes, dislikes, movie_watching_freq, show_watching_freq, reading_freq):
    try:
        conn = sqlite3.connect('Data/users_data.db')
        cursor = conn.cursor()

        cursor.execute('''
            INSERT INTO Users (username, age, gender, fav_entertainment, least_fav_entertainment, likes, dislikes, movie_watching_freq, show_watching_freq, reading_freq)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (username, age, gender, fav_entertainment, least_fav_entertainment, likes, dislikes, movie_watching_freq, show_watching_freq, reading_freq))
        
        conn.commit()
        conn.close()  # Close the connection after committing changes
        print("User profile inserted successfully.")
    except sqlite3.Error as e:
        print(f"Error inserting user profile: {e}")

In [2]:
data.loc[4347]

title                                                    Observe and Report
synopsis                  As head of security at the Forest Ridge Mall, ...
review                    Though it has a mean streak, and does not cate...
genres                                                       comedy, comedy
directors                                                         Jody Hill
authors                                                           Jody Hill
cast                      Seth Rogen, Ray Liotta, Michael PeÃ±a, Anna Far...
runtime                                                              86, 85
production_company                                    Warner Bros. Pictures
original_release_year                                                  2009
streaming_release_year                                                 2011
writer                                                                    0
percentage_mean                                                           0
stars_rating                                                              3
CritiScore                                                               49
Name: 4347, dtype: object

In [3]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer


def get_rating(movie_title):
    # Convert the titles to lowercase for better matching
    data['title'] = data['title'].str.lower()
    movie_title = movie_title.lower()

    # Vectorize the movie titles
    vectorizer = CountVectorizer().fit(data['title'])
    movie_vector = vectorizer.transform([movie_title])

    # Compute cosine similarity between the input movie title and all titles in the dataset
    cosine_similarities = cosine_similarity(movie_vector, vectorizer.transform(data['title']))

    # Find the index of the most similar title
    print(cosine_similarities.max())
    index = cosine_similarities.argmax()
    print(index)
    # Get the corresponding rating
    return data.iloc[index]['CritiScore']

In [4]:
movies = data
def get_rating(movie_title):
        # Convert the titles to lowercase for better matching
        movies['title'] = movies['title'].str.lower()
        movie_title = movie_title.lower()

        # Vectorize the movie titles
        vectorizer = CountVectorizer().fit(movies['title'])
        movie_vector = vectorizer.transform([movie_title])

        # Compute cosine similarity between the input movie title and all titles in the dataset
        cosine_similarities = cosine_similarity(movie_vector, vectorizer.transform(movies['title']))

        # Find the maximum similarity score
        max_similarity = cosine_similarities.max()

        # Compare the maximum similarity score with the threshold
        if max_similarity > 0.7:
            # Get the index of the movie with the maximum similarity score
            index = cosine_similarities.argmax()
            # Get the corresponding rating
            return movies.iloc[index]['CritiScore']
        else:
            return "Not Available"

In [5]:
def extract_movie_titles(text):
    pattern = r'"(.*?)"'
    movie_titles = re.findall(pattern, text)
    return movie_titles

In [6]:
import re

def extract_movie_descriptions(text):
    pattern = r'"[^"]+"\s*\(Movie\)\s*-\s*([^"]+)'
    descriptions = re.findall(pattern, text)
    return descriptions

In [7]:
text = '''Fantastic! In that case, here are some romantic comedy movie recommendations for you:

<<<MOVIES_ON>>>
- "Crazy, Stupid, Love": A charming and hilarious film about love, relationships, and self-discovery.
- "The Proposal": A delightful romantic comedy with a mix of humor and heartwarming moments.
- "10 Things I Hate About You": A modern retelling of Shakespeare's "The Taming of the Shrew" with a perfect blend of romance and comedy.
- "Silver Linings Playbook": A unique and heartfelt story about two individuals finding love and redemption amidst their personal struggles.
- "When Harry Met Sally": A timeless classic that explores the complexities of friendship and love.

I hope you find these recommendations enjoyable! Let me know if there's anything else I can assist you with.
'''
descriptions = extract_movie_descriptions(text)
print(descriptions)
print(type(descriptions))
print(len(descriptions))

[]
<class 'list'>
0

In [45]:
import re

def extract_movie_titles(text):
    pattern = r'^- "(.*?)":'  # Adjusted pattern to match movie titles in the specified format
    movie_titles = re.findall(pattern, text, re.MULTILINE)
    return movie_titles

text = '''
Fantastic! In that case, here are some romantic comedy movie recommendations for you:

<<<MOVIES_ON>>>
- "Crazy, Stupid, Love": A charming and hilarious film about love, relationships, and self-discovery.
- "The Proposal": A delightful romantic comedy with a mix of humor and heartwarming moments.
- "10 Things I Hate About You": A modern retelling of Shakespeare's "The Taming of the Shrew" with a perfect blend of romance and comedy.
- "Silver Linings Playbook": A unique and heartfelt story about two individuals finding love and redemption amidst their personal struggles.
- "When Harry Met Sally": A timeless classic that explores the complexities of friendship and love.

I hope you find these recommendations enjoyable! Let me know if there's anything else I can assist you with.
'''

titles = extract_movie_titles(text)
print(titles)

['Crazy, Stupid, Love', 'The Proposal', '10 Things I Hate About You', 'Silver Linings Playbook', 'When Harry Met Sally']

In [9]:
def extract_descriptions(text):
    descriptions = []
    # Split the text by lines
    lines = text.split('\n')
    # Find lines starting with '- "'
    for line in lines:
        if line.startswith('- "'):
            # Extract the description between the double quotes
            description = line.split(': ')[1]
            descriptions.append(description)
    return descriptions

text = '''
Fantastic! In that case, here are some romantic comedy movie recommendations for you:

<<<MOVIES_ON>>>
- "Crazy, Stupid, Love": A charming and hilarious film about love, relationships, and self-discovery.
- "The Proposal": A delightful romantic comedy with a mix of humor and heartwarming moments.
- "10 Things I Hate About You": A modern retelling of Shakespeare's "The Taming of the Shrew" with a perfect blend of romance and comedy.
- "Silver Linings Playbook": A unique and heartfelt story about two individuals finding love and redemption amidst their personal struggles.
- "When Harry Met Sally": A timeless classic that explores the complexities of friendship and love.

I hope you find these recommendations enjoyable! Let me know if there's anything else I can assist you with.
'''

descriptions = extract_descriptions(text)
print(descriptions)

['A charming and hilarious film about love, relationships, and self-discovery.', 'A delightful romantic comedy with a mix of humor and heartwarming moments.', 'A modern retelling of Shakespeare\'s "The Taming of the Shrew" with a perfect blend of romance and comedy.', 'A unique and heartfelt story about two individuals finding love and redemption amidst their personal struggles.', 'A timeless classic that explores the complexities of friendship and love.']

In [10]:
movie_title_input = input("Enter the movie title: ")
rating = get_rating(movie_title_input)
print(f"The CritiScore for '{movie_title_input}' is: {rating}")

The CritiScore for 'When harry met sally' is: 90

In [11]:
text = '''
"Crazy Rich Asians" (Movie) - A contemporary romantic comedy about a woman who accompanies her boyfriend to Singapore and discovers his wealthy and extravagant family.

"When Harry Met Sally" (Movie) - A classic romantic comedy that follows the complicated relationship between Harry and Sally as they navigate friendship, love, and the age-old question of whether men and women can truly be just friends.

"The Proposal" (Movie) - A hilarious rom-com about a high-powered book editor who forces her assistant to marry her in order to avoid deportation to Canada.'''
rating = extract_movie_titles(text)
print(f"The title is: {rating}")
print(type(rating))

The title is: []
<class 'list'>

In [12]:
movie_title_input = input("Enter the movie title: ")
rating = get_rating(movie_title_input)
print(f"The CritiScore for '{movie_title_input}' is: {rating}")

The CritiScore for '10 things I hate about you' is: 69

In [13]:
data.loc[4349]

title                                                             obsession
synopsis                  Michael Courtland (Cliff Robertson) is a husba...
review                    Obsession suffers in comparison to the Alfred ...
genres                                            drama, mystery & suspense
directors                                                     Brian DePalma
authors                                        Brian DePalma, Paul Schrader
cast                      Cliff Robertson, GeneviÃ¨ve Bujold, John Lithgo...
runtime                                                                  98
production_company                         Sony Pictures Home Entertainment
original_release_year                                                  1976
streaming_release_year                                                 2012
writer                                                                    0
percentage_mean                                                           0
stars_rating                                                              0
CritiScore                                                               66
Name: 4349, dtype: object

In [22]:
shows = pd. read_csv("Data/Metadata/tvshows.csv")
books = pd.read_csv("Data/Metadata/books.csv")

In [23]:
shows.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73786 entries, 0 to 73785
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Series_title  73786 non-null  object
 1   Release_year  73786 non-null  object
 2   Genre         73786 non-null  object
 3   Synopsis      73786 non-null  object
 4   Runtime       73786 non-null  int64
 5   Directors     73786 non-null  object
 6   Cast          73786 non-null  object
 7   CritiScore    73786 non-null  int64
dtypes: int64(2), object(6)
memory usage: 4.5+ MB

In [24]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45270 entries, 0 to 45269
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   title                45270 non-null  object
 1   isbn                 45270 non-null  object
 2   authors              45270 non-null  object
 3   year_of_publication  45270 non-null  object
 4   publisher            45270 non-null  object
 5   description          45270 non-null  object
 6   Language             45270 non-null  object
 7   categories           45270 non-null  object
 8   country              45270 non-null  object
 9   CritiScore           45270 non-null  int64
dtypes: int64(1), object(9)
memory usage: 3.5+ MB

In [25]:
books

,title,isbn,authors,year_of_publication,publisher,description,Language,categories,country,CritiScore
0,"Ask Lily (Young Women of Faith: Lily Series, ...",0310232546,Nancy N. Rue,2001,Zonderkidz,"When Lily enters the seventh grade, she starts...",en,"juvenile, fiction",usa,80
1,Dark Justice,0399151788,Jack Higgins,2004,Putnam Publishing Group,An attempt on the life of the U.S. president d...,en,fiction,usa,100
2,Flight of Fancy: American Heiresses (Zebra Ba...,082177350X,Tracy Cozzens,2002,Kensington Publishing Corporation,"Arriving in Paris with her newly rich family, ...",en,fiction,usa,80
3,Highland Desire (Zebra Splendor Historical Ro...,0821760580,Joyce Carlow,1998,Zebra Books,"At 17, Glynis MacPherson can out-shoot, out-ri...",en,fiction,usa,70
4,Microsoft Application Architecture For Micros...,0735618372,Microsoft Corporation Staff,2004,Microsoft Press,This guide assumes you are familiar with .NET ...,en,computers,usa,90
...,...,...,...,...,...,...,...,...,...,...
45265,"tick, tick ... BOOM!",0,['Jonathan Larson'],1997,Harper Collins,"In these pages, Rent offers what most theater ...",0,drama,0,80
45266,why I'm like this : True Stories,006051261X,Cynthia Kaplan,2003,Perennial,A collection of humorous personal essays inclu...,en,biography & autobiography,usa,70
45267,ÃÂ¿Eres tu mi mamÃÂ¡?/Are You My Mother?,0394815963,Philip D. Eastman,1967,Random House Books for Young Readers,Un pequeÃ±o pajarito ha salido del huevo mientr...,es,"juvenile, fiction",usa,90
45268,"ÃÂ¿QuÃÂ© me quieres, amor?",8495501104,Manuel Rivas,2001,Santillana USA Publishing Company,Each short story of this book is a magic spell...,es,fiction,spain,60
45269,Ã?ngeles fugaces (Falling Angels),8420451398,Tracy Chevalier,2002,"Alfaguara Ediciones, S.A. (Spain)",ENGLISH DESCRIPTIONAnother dazzling novel b th...,es,fiction,spain,40

In [30]:
shows

,Series_title,Release_year,Genre,Synopsis,Runtime,Directors,Cast,CritiScore
0,HBO Storybook Musicals,1987â,"animation, family, musical",Mike and his trusty shovel Mary Anne are known...,26,Michael Sporn,"Robert Klein, Jason Biggs, Tina Fabrique, She...",70
1,Jurassic World: Camp Cretaceous,2020â2022,"animation, action, adventure","Based on the show Camp Cretaceous, Hidden Adve...",32,"Leah Artwick, Eric Elrod, Michael Mullen, Zes...","Paul-MikÃ©l Williams, Sean Giambrone, Kausar M...",70
2,SMG4,2011â,"animation, action, adventure",SMG4 goes insane and it's up to his friends to...,39,Luke Lerdwichagul,"James Bailey, Kevin Lerdwichagul, Luke Lerdwi...",70
3,#1 Cheerleader Camp,2010 Video,comedy,A pair of horny college guys get summer jobs a...,95,Mark Quod,"Charlene Tilton, Seth Cassell, Jay Gillespie,...",30
4,#69 Samskar Colony,2022,romance,"Koushik, a teenage boy, moves to the city with...",126,Suneel Kumar Reddy,"Ajay, Fm Babai, Badram, Bapiraju",60
...,...,...,...,...,...,...,...,...
73781,Ãbermut im Salzkammergut,1963,"comedy, musical",Birgit is a model from the city and sweetheart...,99,Hans Billian,"Claus Biederstaedt, Helga Sommerfeld, Margitt...",50
73782,ÃÃ§ Harfliler: Adak,2019,"horror, thriller",Salih was shot with a rifle in the forest wher...,91,Alper MestÃ§i,"Ramazan Demir, Ceren Yilmaz, Ejder Ãzkarsligi...",40
73783,ÃÃ§ Kiz Kardes,(2022â ),drama,The tale of three sisters and the obstacles th...,150,0,"Reha Ãzcan, Iclal Aydin, Berker GÃ¼ven, ÃzgÃ¼ Kaya",40
73784,ÃÃ§ Kurus,(2021â2022),"action, crime, drama",When a serial killer stalks a Romani neighborh...,120,0,"Uraz Kaygilaroglu, Ekin KoÃ§, Aslihan Malbora, ...",70
73785,ÎÎ±ÏÎ±Î³ÎºÎ¹ÏÎ¶Î·Ï the Movie,2022,"animation, comedy, family",Add a Plot,74,"Akis Karras, Christos Leivaditis, Ekaterini P...","Athos Danellis, Elena Maragou",60

In [36]:
def get_rating(data, data_column, title):
        # Convert the titles to lowercase for better matching
        data_column = data_column.str.lower()
        title = title.lower()

        # Vectorize the movie titles
        vectorizer = CountVectorizer().fit(data_column)
        data_vector = vectorizer.transform([title])

        # Compute cosine similarity between the input movie title and all titles in the dataset
        cosine_similarities = cosine_similarity(data_vector, vectorizer.transform(data_column))

        # Find the maximum similarity score
        max_similarity = cosine_similarities.max()
        print(max_similarity)
        # Compare the maximum similarity score with the threshold
        if max_similarity > 0.6:
            # Get the index of the movie with the maximum similarity score
            index = cosine_similarities.argmax()
            # Get the corresponding rating
            return data.iloc[index]['CritiScore']
        else:
            return "Not Available"

In [28]:
movie_title_input = input("Enter the movie title: ")
rating = get_rating(movies, movies['title'],movie_title_input)
print(f"The CritiScore for '{movie_title_input}' is: {rating}")

The CritiScore for '10 things I hate about you' is: 69

In [31]:
shows_title_input = input("Enter the show title: ")
rating_show = get_rating(shows, shows['Series_title'], shows_title_input)
print(f"The CritiScore for '{shows_title_input}' is: {rating_show}")

The CritiScore for 'Jurassic World' is: 60

In [37]:
books_title_input = input("Enter the book title: ")
rating_books = get_rating(books, books['title'],books_title_input)
print(f"The CritiScore for '{books_title_input}' is: {rating_books}")

0.6666666666666669
The CritiScore for 'Flight of Fancy' is: 50

In [47]:
def extract_book_titles(text):
    pattern = r'"(.*?)" by'  # Updated pattern to capture movie/book titles only
    book_titles = re.findall(pattern, text)
    return book_titles

In [48]:
text1 = '''- "Twilight" by Stephenie Meyer: A captivating love story between a human girl and a vampire. CritiScore: 8.5/10
- "A Discovery of Witches" by Deborah Harkness: A tale of forbidden love between a witch and a vampire, set in a world of magic and mystery. CritiScore: 9/10
- "Dark Lover" by J.R. Ward: The first book in the popular Black Dagger Brotherhood series, featuring a passionate romance between a vampire warrior and a human woman. CritiScore: 8/10'''


rating1 = extract_book_titles(text1)
print(f"The title is: {rating1}")
print(type(rating1))

The title is: ['Twilight', 'A Discovery of Witches', 'Dark Lover']
<class 'list'>